# Generated by Django 5.2.6 on 2025-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
